version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - your_network
    depends_on:
      - postgres
      - flyway
      - localstack
      - mongodb

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: popo_24
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    networks:
      - your_network

  flyway:
    image: boxfuse/flyway:latest-alpine
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - postgres
    command: ["-url=jdbc:postgresql://localhost:5432/popo_24", "-user=your_user", "-password=your_password", "-connectRetries=60", "migrate"]
    network_mode: "host"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    networks:
      - your_network

  pytest:
    build:
      context: .
      dockerfile: Dockerfile.pytest
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - your_network
    depends_on:
      - postgres
      - flyway
      - localstack

  schemaspy:
    image: schemaspy/schemaspy
    depends_on:
      - postgres
    command: ["-t", "pgsql", "-host", "postgres", "-db", "popo_24", "-u", "your_user", "-p", "your_password"]
    ports:
      - "8080:8080"
    networks:
      - your_network

  stripe-cli:  # Modified service for Stripe CLI
    image: stripe/stripe-cli
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
    command: ["listen", "--skip-verify", "--forward-to=cloudkitchen-be_app_1:8000/api/v1/stripe-payment/webhook"]
    networks:
      - your_network
    depends_on:
      - app

  stripe-cli-trigger:  # Modified service for Stripe CLI
    image: stripe/stripe-cli
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
    command: ["trigger", "customer.subscription.deleted"]
    networks:
      - your_network

    depends_on:
      - app

  mongodb:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"   
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - your_network

networks:
  your_network:
