from pydantic import BaseModel


class STATUS(BaseModel):
    JUST_ORDERED: str
    WAITING_FOR_SELLER_CONFIRM: str
    SELLER_CONFIRMED: str
    ORDER_PROCESSING: str
    SHIPPED: str
    ORDER_COMPLETE: str
    SOFT_DELETE: str
    ACTIVE: str


Status = STATUS(
    JUST_ORDERED="JUST_ORDERED",
    WAITING_FOR_SELLER_CONFIRM="WAITING_FOR_SELLER_CONFIRM",
    SELLER_CONFIRMED="SELLER_CONFIRMED",
    ORDER_PROCESSING="ORDER_PROCESSING",
    SHIPPED="SHIPPED",
    ORDER_COMPLETE="ORDER_COMPLETE",
    SOFT_DELETE="SOFT_DELETE",
    ACTIVE="ACTIVE",
)
