name: CI

on:
  push:
    branches:
      - main
      - '*'

jobs:
  build-and-push-main:
    name: Build and Push Docker Image (Main Branch)
    if: github.ref == 'refs/heads/main'  # Execute only for main branch
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private

      - name: Build Docker image
        run: docker build -t ${{ secrets.ECR_URI }}:${GITHUB_SHA} .

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.ECR_URI }}:${GITHUB_SHA}


  build-only:
    name: Build Docker Image (Other Branches)
    if: github.ref != 'refs/heads/main'  # Execute for all branches except main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t popo24_backend:${GITHUB_SHA} .
